[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=58", "wheel"]

[project]
authors = [
  {name = "Vincent Deo", email = "vdeo@naoj.org"}
]
dependencies = [
  "docopt",
  "libtmux",
  "pygame",
  #"pyMilk", DO NOT - there is a pyMilk on pipy which is a completely different thing.
  "numpy",
  "tqdm",
]

description = "AO188 upgraded RTS codebase"
name = "aorts"
readme = "README.md"
version = "1.0"

[tool.setuptools]
packages = ["aorts"]
script-files = [
  './scripts/rts_start.sh'
]

# [project.scripts]


[tool.pyright]
extraPaths = ["/home/vdeo/src/swmain",] # Need to list scexao's pip install -e packages...
typeCheckingMode = "basic" # off | basic | standard | strict # Look there https://github.com/microsoft/pyright/blob/main/docs/configuration.md
include = ["camstack"]
exclude = ["build/",
           "**/__pycache",
           "**/.mypy_cache",
           ]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.10"
pythonPlatform = "Linux"
