#===============================================================================
# File: Constants.py
#     : Rtm gui constants
#
#===============================================================================
VERSION = 1.3
DGPRAD = 57.295  # Degrees per radian = (360 / 2*pi )
RESERVEDPORTSTOP = 1024  # legal user ports must be greater than this value
CONFIGFILE = "rtmConfig.yaml"  # configuration file
POLYGONFILE = "MirrorWidget_polygons.cfg"
LOGFILE = "rtm.log"
LOGDIR = "/home/ao/ao188/log"  # default logpath

# RATES
RTSFRAMERATE = 10  # target data rate in Hz
DBGLEVEL_RATE2 = 7  # probably  1Hz
DBGLEVEL_RATE1 = 8  # probably 10Hz
DBGLEVEL_RCVONLY = 99

TZONE_LOCAL = 'LOC'  # Local time-zone
TZONE_UTC = 'UTC'  # UTC  time-zone

# Default Values
DFLT_FRAMES_PER_EYE = 1
DFLT_FRAMES_PER_LABEL = 10
DFLT_FRAMES_PER_SHARROW = 2
DFLT_FRAMES_PER_MOUNTPLOT = 5
DFLT_FRAMES_PER_CHART = 10
DFLT_DATAPORT = 12345  # Rtm-gui port for Rx of realtime data
DFLT_RTD_HOST = '10.0.0.6'  # default realtime-data-host
DFLT_RTD_PORT = 25010  # default realtime-data-host port

DFLT_STRIPCHART_TZONE = TZONE_LOCAL  # stripchart time-zone for labels
DFLT_STRIPCHART_HOURS = 12
DFLT_STRIPCHART_MINUTES = DFLT_STRIPCHART_HOURS * 60
DFLT_STRIPCHART_SECONDS = DFLT_STRIPCHART_MINUTES * 60
DFLT_STRIPCHART_BUFFERSIZE = DFLT_STRIPCHART_SECONDS

DFLT_ZEROSCALEBASE = False

# Fixed scale thumbwheel settings for 4 stripcharts 2 wheels per chart
#
# stripchart1 2 wheels

DFLT_SCALEWHEEL1_MAX = 100000
DFLT_SCALEWHEEL1_MIN = -100000
DFLT_SCALEWHEEL1_ROTS = 10000
DFLT_FIXEDSCALE1_MAX = 101
DFLT_FIXEDSCALE1_MIN = 0

# stripchart2 2 wheels
DFLT_SCALEWHEEL2_MAX = 10000
DFLT_SCALEWHEEL2_MIN = -10000
DFLT_SCALEWHEEL2_ROTS = 1000
DFLT_FIXEDSCALE2_MAX = 101
DFLT_FIXEDSCALE2_MIN = 0

# stripchart3 2 wheels
DFLT_SCALEWHEEL3_MAX = 10000
DFLT_SCALEWHEEL3_MIN = -10000
DFLT_SCALEWHEEL3_ROTS = 100
DFLT_FIXEDSCALE3_MAX = 6
DFLT_FIXEDSCALE3_MIN = 0

# stripchart4 2 wheels
DFLT_SCALEWHEEL4_MAX = 10000
DFLT_SCALEWHEEL4_MIN = -10000
DFLT_SCALEWHEEL4_ROTS = 10
DFLT_FIXEDSCALE4_MAX = 10
DFLT_FIXEDSCALE4_MIN = 0

SECONDS_SCALE_SHIFT = 10  # stripchart seconds scale leftshift seconds
MINUTES_SCALE_SHIFT = 60  # stripchart minutes scale leftshift seconds
HOURS_SCALE_SHIFT = 1800  # stripchart hours   scale leftshift seconds

RTD_CONNECT_CMD = "cntmongui connect"
RTD_DISCONNECT_CMD = "cntmongui disconnect"

# Mouse button-codes
LB = 1  # Left Button
MB = 4  # Middle Button
RB = 2  # Right Button

STR, BOOL, INT, FLT = range(4)  # Some datatype codes

# codes for hours/minutes/seconds.  Also values in seconds
HOURS = 3600
MINUTES = 60
SECONDS = 1

# Connection states
DISCONNECTED = 0
CONNECTED = 1

# Colormap Indices
GREYCMAP = 1
SAFETYCMAP = 2
GREENCMAP = 3

# Alarm States
HIGHALARM = 2
LOWALARM = 1
NOALARM = False

# Some colors
BLACK = '#000000'
DESATRED = '#F88B8B'  # '#FF6060'
DESATGREEN = '#A9F199'
DESATYELLOW = '#FFFF64'
DESATBLUE = '#A6C1EE'
DESATORANGE = '#FABA00'  # '#EDECEB'
DESATPURPLE = '#E680ED'
BKGBLACK = '#606060'
FRGGREEN = '#00FF00'
MWINBKGCOLOR = '#DBDBDB'
BKGORANGE = '#FABA00'  # '#EDECEB'
ORANGE = '#F6BD18'
TURQUE = '#0DA1F4'
CELLALARMRED = '#FF0000'
CELLALARMYLW = '#FFFF00'
STRIPCHARTGRID = '#A5CD99'  # stripchart grid color
TTPLOTBACKGROUND = '#000000'  # tiptilt plot background
TTPLOTGRID = STRIPCHARTGRID
SETALARMPOPUPBKG = '#C4E9FF'
#SETALARMPOPUPBKG = '#A6F1E6'
#SILVERGRAY       = '#C6CCD0'
ALARMRED = DESATRED
ALARMYELLOW = DESATYELLOW
LBLFGCOLOR = BLACK
LBLBKGCOLOR = MWINBKGCOLOR

NGS_MATRIX = 0
LGS_MATRIX = 1
LOOPSTATUS_ON = 1
LOOPSTATUS_OFF = 0
VMDRIVE_ON = 1
VMDRIVE_OFF = 0

# Min/Max for some plots
DMMIN = -400
DMMAX = 400
CRVMIN = 0
CRVMAX = 1
APDMIN = 0
APDMAX = 2000
SHMIN = -1
SHMAX = 1
NMRRCELLS = 188

#
# RT Data Indices (numpy style)
#
RTDATACHUNKSIZE = 5000  # this many bytes per frame
HEADER_START = 0
HEADER_SIZE = 32
HEADER_END = HEADER_START + HEADER_SIZE
DM_CELLDATASTART = 0  # After 32 byte Header
DM_CELLDATAEND = NMRRCELLS  # 188
CRV_CELLDATASTART = DM_CELLDATAEND  # 188
CRV_CELLDATAEND = 376
APD_CELLDATASTART = 376
APD_CELLDATAEND = 564
SH_CELLDATASTART = 564
SH_CELLDATAEND = 580
GENDATASTART = 580

# Offsets in float-array within general data (GENDATA) subsection
FRAME_NUMBER = 0
VMDRIVE = 1
VMFREQ = 2
VMVOLT = 3
VMPHASE = 4
LOOPSTATUS = 5
DMGAIN = 6
DMGAINHOLD = 7
TTGAIN = 8
TTGAINHOLD = 9
PSUBGAIN = 10
PSUBGAINHOLD = 11
STTGAIN = 12
STTGAINHOLD = 13
HTTGAIN = 14
HDFGAIN = 15
LTTGAIN = 16
LDFGAIN = 17
WTTGAIN = 18
ADFGAIN = 19
CTRLMTRXSIDE = 20
APDSAFETY = 21
DMSAFETY = 22
DM_CELLDATAMIN = 23
DM_CELLDATAMAX = 24
DM_CELLDATAVAR = 25
DM_CELLDATAAVG = 26
DM_TTMODEX = 27
DM_TTMODEY = 28
DM_TTMODEVAR = 29
DM_DEFOCUS = 30  # dm defocus slider: -1 to 1
DM_DEFOCUSVAR = 31  #
DM_FLATVAR = 32
DM_TIMEVAR = 33
DM_TTMOUNTX = 34  # -9 to 9 top tiptilt mount plot
DM_TTMOUNTY = 35  # -9 to 9 top tiptilt mount plot
DM_TTMOUNTVAR = 36
DM_TTMOUNTFLATVAR = 37
DM_TTMOUNTTIMEVAR = 38
CRV_CELLDATAMIN = 39
CRV_CELLDATAMAX = 40
CRV_CELLDATAVAR = 41
CRV_CELLDATAAVG = 42
CRV_TTMODEX = 43
CRV_TTMODEY = 44
CRV_TTMODEVAR = 45
CRV_DEFOCUS = 46  # crv defocus slider -1 to 1 usually -0.1 to 0.1
CRV_DEFOCUSVAR = 47
CRV_FLATVAR = 48
CRV_TIMEVAR = 49
CRV_WAVEFRONTERROR = 50
APD_CELLDATAMIN = 51
APD_CELLDATAMAX = 52
APD_CELLDATAVAR = 53
APD_CELLDATAAVG = 54  # changed APD_CELLCOUNTAVG APD_CELLDATAAVG
APD_RMAGAVG = 55
LWF_DATAMIN = 56
LWF_DATAMAX = 57
LWF_DATAVAR = 58
LWF_COUNTAVG = 59
LWF_RMAGAVG = 60  # sh label: rmag
LWF_TTMODEX = 61  # sh dot plot -1 to 1
LWF_TTMODEY = 62  # sh dot plot -1 to 1
LWF_TTMODEVAR = 63
LWF_DEFOCUS = 64  # sh defocus slider
LWF_DEFOCUSVAR = 65
SH_Q1TTMODEX = 66
SH_Q1TTMODEY = 67
SH_Q2TTMODEX = 68
SH_Q2TTMODEY = 69
SH_Q3TTMODEX = 70
SH_Q3TTMODEY = 71
SH_Q4TTMODEX = 72
SH_Q4TTMODEY = 73
WFS_TTCH1 = 74  # 0 to 10 bot tiptilt mount plot X
WFS_TTCH2 = 75  # 0 to 10 bot tiptilt mount plot Y
WFS_VAR = 76
IRM2TTX = 77
IRM2TTY = 78
IRM2TTVAR = 79
GENDATASZ = 80
GENDATAEND = GENDATASTART + GENDATASZ
