#!/bin/env python
'''
Set the DM TT value.

off: offset mode, write to channel 0 of TT DMcomb
abs: absolute mode, overwrite output of TT DMcomb

Usage:
	setwtt abs (0|1) <val>
	setwtt incr <tip> <tilt>
'''

SHM_ABSPOINT = f'wtt_value_float'

import numpy as np
from pyMilk.interfacing.shm import SHM
from docopt import docopt

args = docopt(__doc__)

if args['incr']:
	s = SHM(SHM_ABSPOINT)
	tip = float(args['<tip>'])
	tilt = float(args['<tip>'])

	tt = s.get_data()
	tt[0] += tip
	tt[1] += tilt
	s.set_data(tt)

elif args['off'] or args['abs']:
	s = SHM(SHM_ABSPOINT)
	tt = s.get_data()

	val = float(args['<val>'])

	if args['0']:
		s.set_data(np.array([val, tt[1]], np.float32))
	else:
		s.set_data(np.array([tt[0], val], np.float32))