#!/usr/bin/env bash

ACTX=20
ACTY=20

NBITER=${1:-10}

echo "NBITER = ${NBITER}"

for i in {0..9999}
do
if [[ $i -lt ${NBITER} ]]; then
  i2=$(printf "%04d" $i)
  echo "iteration  $i2"
  OUTFILE="mlatseq.$i2.fits"
  echo "output : $OUTFILE"
  if [ -f $OUTFILE ];
  then
    echo "   File already exists ... skipping"
  else

    echo "Closing loop"
    cacao-fpsctrl setval mfilt loopON ON

    cd ../ttoff3k-rootdir
    cacao-fpsctrl setval mfilt loopON ON
    cd -

    sleep 2
    echo "Opening loop"
    cacao-fpsctrl setval mfilt loopON OFF

    cd ../ttoff3k-rootdir
    cacao-fpsctrl setval mfilt loopON OFF
    cd -

    cacao-aorun-020-mlat -a -ax $ACTX -ay $ACTY -w
    cp nir3k-rundir/fps.mlat-7.datadir/mlat-diffseq.fits ${OUTFILE}

  fi
  echo "end iteration"
fi
done
