#!/usr/bin/env bash

# Fix rootdir for nested scripts/ loop scripts!
cd ${HOME}/AOloop/nir3k-rootdir

SVDl100=${1:-"08"}
echo "SVDl100 = ${SVDl100}"


MARGMODE=${2:-1}
# 1: always marginalize against TT in DM space

WHICH_MARG="-marg"
MARGTT="-margDM 0:1"
margstring="margDM01-margWFS"


if [[ ${MARGMODE} -eq 1 ]]; then
echo "MARGMODE = 1"
WHICH_MARG="-marg"
MARGTT="-margDM 0:1"
margstring="margDM01-margWFS"
fi


if [[ ${MARGMODE} -eq 2 ]]; then
echo "MARGMODE = 2"
WHICH_MARG="-marg"
margstring="margWFS"
fi

if [[ ${MARGMODE} -eq 3 ]]; then
echo "MARGMODE = 2"
WHICH_MARG="-margDM"
margstring="margDM"
fi







SAVEDIR="calib/svd${SVDl100}-${margstring}/"

SAVEDIR=${3:-"${SAVEDIR}"}
echo "SAVEDIR : ${SAVEDIR}"




SVDlim="0.${SVDl100}"

echo "SVDlim = ${SVDlim}"

# 0.08  1745
# 0.10	1535
# 0.12  1390








if [ ! -d ${SAVEDIR} ]; then

cacao-fpsctrl setval compstrCM svdlim ${SVDlim}

# Make T CM
cacao-aorun-039-compstrCM -mb 0 -mr 1:1


# Make T CM
cacao-fpsctrl setval compstrCM svdlim ${SVDlim}
cacao-aorun-039-compstrCM -mb 1 -mr 2:2

# make LO CM
cacao-fpsctrl setval compstrCM svdlim ${SVDlim}

if [[ ${MARGMODE} -eq 1 ]]; then
cacao-aorun-039-compstrCM -mb 2 -mr 3:12 ${MARGTT}
else
cacao-aorun-039-compstrCM -mb 2 -mr 3:12 ${WHICH_MARG} 0:1
fi



# make LO CM
cacao-fpsctrl setval compstrCM svdlim ${SVDlim}

if [[ ${MARGMODE} -eq 1 ]]; then
cacao-aorun-039-compstrCM -mb 3 -mr 13:50 ${WHICH_MARG} 2 ${MARGTT}
else
cacao-aorun-039-compstrCM -mb 3 -mr 13:50 ${WHICH_MARG} 0:1:2
fi



# make MO CM
cacao-fpsctrl setval compstrCM svdlim ${SVDlim}

if [[ ${MARGMODE} -eq 1 ]]; then
cacao-aorun-039-compstrCM -mb 4 -mr 51:200 ${WHICH_MARG} 2:3 ${MARGTT}
else
cacao-aorun-039-compstrCM -mb 4 -mr 51:200 ${WHICH_MARG} 0:1:2:3
fi



# make HO CM
cacao-fpsctrl setval compstrCM svdlim ${SVDlim}

if [[ ${MARGMODE} -eq 1 ]]; then
cacao-aorun-039-compstrCM -mb 5 -mr 201:1000 ${WHICH_MARG} 2:3:4 ${MARGTT}
else
cacao-aorun-039-compstrCM -mb 5 -mr 201:1000 ${WHICH_MARG} 0:1:2:3:4
fi



# make HHO CM
cacao-fpsctrl setval compstrCM svdlim ${SVDlim}
# 5029
if [[ ${MARGMODE} -eq 1 ]]; then
cacao-aorun-039-compstrCM -mb 6 -mr 1001:2029 ${WHICH_MARG} 2:3:4:5 ${MARGTT}
else
cacao-aorun-039-compstrCM -mb 6 -mr 1001:2029 ${WHICH_MARG} 0:1:2:3:4:5
fi


# merge CMs
cacao-aorun-039-compstrCM -mbm 0:1:2:3:4:5:6





mkdir -p ${SAVEDIR}
cp conf/CMmodesDM.fits ${SAVEDIR}
cp conf/CMmodesWFS.fits ${SAVEDIR}
cp conf/CMmodesDM.xp.fits ${SAVEDIR}
cp conf/CMmodesWFS.xp.fits ${SAVEDIR}

else

echo "DIRECTORY ${SAVEDIR} exists"

cp ${SAVEDIR}/CMmodesDM.fits ./conf/
cp ${SAVEDIR}/CMmodesWFS.fits ./conf/
cp ${SAVEDIR}/CMmodesDM.xp.fits ./conf/
cp ${SAVEDIR}/CMmodesWFS.xp.fits ./conf/

fi


milk-FITS2shm ./conf/CMmodesDM.fits aol7_DMmodes
milk-FITS2shm ./conf/CMmodesWFS.fits aol7_modesWFS

cacao-fpsctrl runstop wfs2cmodeval 0 0
cacao-fpsctrl runstop mfilt 0 0
cacao-fpsctrl runstop mvalC2dm 0 0

cacao-fpsctrl confstop wfs2cmodeval 0 0
cacao-fpsctrl confstop mfilt 0 0
cacao-fpsctrl confstop mvalC2dm 0 0

sleep 2

# START

cacao-fpsctrl confstart wfs2cmodeval 0 0
sleep 1
cacao-fpsctrl runstart wfs2cmodeval 0 0

sleep 2

cacao-fpsctrl confstart mfilt 0 0
sleep 1
cacao-fpsctrl runstart mfilt 0 0
#cacao-fpsctrl setval mfilt loopON ON
#cacao-fpsctrl setval mfilt loopgain 0.0


sleep 2

cacao-fpsctrl confstart mvalC2dm 0 0
sleep 1
cacao-fpsctrl runstart mvalC2dm 0 0

echo "Done"
