#!/usr/bin/env bash

# Fix rootdir for nested scripts/ loop scripts!
cd ${HOME}/AOloop/nir3k-rootdir

milk-all << EOF
imgen.mkdisk d00 160 160 40 40 40
imgen.mkdisk d10 160 160 120 40 40
imgen.mkdisk d11 160 160 120 120 40
imgen.mkdisk d01 160 160 40 120 40
mask=d00+d01+d11+d10
saveFITS mask "./conf/wfsmask.fits"
exitCLI
EOF
milk-FITS2shm "./conf/wfsmask.fits" aol7_wfsmask
