#!/usr/bin/env bash

TYPE=1

./nir3k_compCM 14 ${TYPE}
./nir3k_compCM 12 ${TYPE}
./nir3k_compCM 10 ${TYPE}
./nir3k_compCM 08 ${TYPE}
./nir3k_compCM 06 ${TYPE}
./nir3k_compCM 04 ${TYPE}
./nir3k_compCM 02 ${TYPE}
./nir3k_compCM 01 ${TYPE}
