#!/usr/bin/env bash

# Fix rootdir for nested scripts/ loop scripts!
cd ${HOME}/AOloop/nir3k-rootdir

milk-all << EOF
readshmim dm64disp04
zern.mkzer zfoc 64 3 32.0
zfoc1=zfoc*$1
cp zfoc1 dm64disp04
#saveFITS zfoc1 zfoc.fits
#listim
exitCLI
EOF
