#!/usr/bin/env bash

# Fix rootdir for nested scripts/ loop scripts!
cd ${HOME}/AOloop/nir3k-rootdir

while [ ! -f takeRM.stop ] ; do
    cacao-aorun-030-acqlinResp HpokeC -n 4
    cacao-aorun-031-RMHdecode
    sleep 5
done
rm takeRM.stop
