GsMode:
  alarmHi: {desc: 'Guidestar mode high alarm ', enable: false, label: 'Guidestar mode
      high alarm ', value: 0.0}
  alarmLow: {desc: 'Guidestar mode low alarm ', enable: false, label: 'Guidestar mode
      low alarm ', value: 0.0}
  dataNdx: 20
  desc: Guide-Star mode
  label: GsMode
adfgain:
  alarmHi: {desc: '', enable: false, label: 'Adf gain high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Adf gain low alarm ', value: 0.0}
  dataNdx: 19
  desc: 'Acquisition Unit #1 defocus offload Gain'
  label: AdfGain
apdAvg:
  alarmHi: {desc: ' ', enable: false, label: apd Avg high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: apd Avg low alarm, value: 0.0}
  dataNdx: 54
  desc: Avelanche-photo-diode average count
  label: Avg
apdMax:
  alarmHi: {desc: ' ', enable: false, label: apd Max high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: apd Max low alarm, value: 0.0}
  dataNdx: 52
  desc: Avelanche-photo-diode maximum count
  label: Max
apdMin:
  alarmHi: {desc: apd Min high alarm threshold, enable: false, label: apd Min high
      alarm, value: 0.0}
  alarmLow: {desc: apd Min low alarm threshold, enable: false, label: apd Min low
      alarm, value: 0.0}
  dataNdx: 51
  desc: Avelanche-photo-diode minimum count
  label: Min
apdRmag:
  alarmHi: {desc: ' ', enable: false, label: APD Rmag high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: APD Rmag low alarm, value: 0.0}
  dataNdx: 55
  desc: Avelanche-photo-diode R-magnitude
  label: Rmag
apdeye:
  alarmHi: {desc: Avalanche Photodiode eye high alarm threshold, enable: false, label: Apd
      eye high alarm, value: 0.0}
  alarmLow: {desc: Avalanche Photodiode eye high alarm threshold, enable: false, label: Apd
      eye low alarm, value: 0.0}
  dataNdx: 376
  desc: Avelanche-Photo-Diode Mirror-Map
  label: APD Eye
crvAvg:
  alarmHi: {desc: ' ', enable: false, label: Curvature Avg high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: Curvature Avg low alarm, value: 0.0}
  dataNdx: 42
  desc: Curvature average count
  label: Avg
crvDefocus:
  alarmHi: {desc: Curvature Defocus high alarm threshold, enable: false, label: Curvature
      Defocus high alarm, value: 0.0}
  alarmLow: {desc: Curvature Defocus low alarm threshold, enable: false, label: Curvature
      Defocus low alarm, value: 0.0}
  dataNdx: 46
  desc: Curvature defocus
  label: Defocus
crvMax:
  alarmHi: {desc: ' ', enable: false, label: Curvature Max high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: Curvature Max low alarm, value: 0.0}
  dataNdx: 40
  desc: Curvature maximum count
  label: Max
crvMin:
  alarmHi: {desc: Curvature Min high alarm threshold, enable: false, label: Curvature
      Min high alarm, value: 0.0}
  alarmLow: {desc: Curvature Min low alarm threshold, enable: false, label: Curvature
      Min low alarm, value: 0.0}
  dataNdx: 39
  desc: Curvature minimum count
  label: Min
crvTiltX:
  alarmHi: {desc: Curvature TiltX high alarm threshold, enable: false, label: Curvature
      TiltX high alarm, value: 0.0}
  alarmLow: {desc: Curvature TiltY low alarm threshold, enable: false, label: Curvature
      TiltY low alarm, value: 0.0}
  dataNdx: 43
  desc: Curvature X-axis tilt
  label: TiltX
crvTiltY:
  alarmHi: {desc: Curvature TiltY high alarm threshold, enable: false, label: Curvature
      TiltY high alarm, value: 0.0}
  alarmLow: {desc: Curvature TiltY low alarm threshold, enable: false, label: Curvature
      TiltY low alarm, value: 0.0}
  dataNdx: 44
  desc: Curvature Y-axis tilt
  label: TiltY
crveye:
  alarmHi: {desc: Curvature eye high alarm, enable: false, label: Curvature eye high
      alarm, value: 0.0}
  alarmLow: {desc: Curvature eye low alarm, enable: false, label: Curvature eye low
      alarm, value: 0.0}
  dataNdx: 188
  desc: Curvature Mirror-Map
  label: Curvature Mirror-Map
ctrlmatrix:
  alarmHi: {desc: '', enable: false, label: 'Control matrix side high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Control matrix side low alarm ', value: 0.0}
  dataNdx: 20
  desc: Control Matrix Guide-star mode
  label: Ctrl Matrix
dmAvg:
  alarmHi: {desc: ' ', enable: false, label: dm Avg high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: dm Avg low alarm, value: 0.0}
  dataNdx: 26
  desc: Deformable Mirror average count
  label: Avg
dmDefocus:
  alarmHi: {desc: dm Defocus high alarm threshold, enable: false, label: dm Defocus
      high alarm, value: 0.0}
  alarmLow: {desc: dm Defocus low alarm threshold, enable: false, label: dm Defocus
      low alarm, value: 0.0}
  dataNdx: 30
  desc: Deformable Mirror Defocus
  label: Defocus
dmMax:
  alarmHi: {desc: ' ', enable: false, label: dm Max high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: dm Max low alarm, value: 0.0}
  dataNdx: 24
  desc: Deformable Mirror maximum count
  label: Max
dmMin:
  alarmHi: {desc: dm Min high alarm threshold, enable: false, label: dm Min high alarm,
    value: 0.0}
  alarmLow: {desc: dm Min low alarm threshold, enable: false, label: dm Min low alarm,
    value: 0.0}
  dataNdx: 23
  desc: Deformable Mirror minimum count
  label: Min
dmTiltX:
  alarmHi: {desc: dm TiltX high alarm threshold, enable: false, label: dm TiltX high
      alarm, value: 0.0}
  alarmLow: {desc: dm TiltX low alarm threshold, enable: false, label: dm TiltX low
      alarm, value: 0.0}
  dataNdx: 27
  desc: Deformable Mirror X-axis tilt
  label: TiltX
dmTiltY:
  alarmHi: {desc: dm TiltY high alarm threshold, enable: false, label: dm TiltY high
      alarm, value: 0.0}
  alarmLow: {desc: dm TiltY low alarm threshold, enable: false, label: dm TiltY low
      alarm, value: 0.0}
  dataNdx: 28
  desc: Deformable Mirror Y-axis tilt
  label: TiltY
dmTtMountX:
  alarmHi: {desc: '', enable: false, label: DM tiptilt-mount X high alarm, value: 0.0}
  alarmLow: {desc: '', enable: false, label: DM tiptilt-mount X low alarm, value: 0.0}
  dataNdx: 34
  desc: Deformable Mirror TipTilt mount X-axis value
  label: DM Tiptilt Mount X
dmTtMountY:
  alarmHi: {desc: '', enable: false, label: DM tiptilt-mount Y high alarm, value: 0.0}
  alarmLow: {desc: '', enable: false, label: DM tiptilt-mount Y low alarm, value: 0.0}
  dataNdx: 35
  desc: Deformable Mirror TipTilt mount Y-axis value
  label: DM Tiptilt Mount Y
dmeye:
  alarmHi: {desc: dm eye high alarm threshold, enable: false, label: dm eye high alarm,
    value: 0.0}
  alarmLow: {desc: dm eye low alarm threshold, enable: false, label: dm eye low alarm,
    value: 0.0}
  dataNdx: 0
  desc: Deformable Mirror-Map
  label: Deformable Mirror-Map
dmgain:
  alarmHi: {desc: Dm gain high alarm, enable: false, label: Dm gain high alarm, value: 0.0}
  alarmLow: {desc: '', enable: false, label: Dm gain low alarm, value: 0.0}
  dataNdx: 6
  desc: Deformable Mirror gain
  label: DmGain
dmgainHold:
  alarmHi: {desc: 'Dm gain hold high alarm ', enable: false, label: 'Dm gain hold
      high alarm ', value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: 'Dm gain hold low alarm ', value: 0.0}
  dataNdx: 7
  desc: Deformable Mirror gain hold
  label: hold
gen:
  ScreenX: {desc: Window X startup coordinate, label: Start window at screen X Coordinate,
    value: 10}
  ScreenY: {desc: Window Y startup Coordinate, label: Start window at screen Y Coordinate,
    value: '50'}
  configpath: {desc: Config-file path, label: Config path, value: null}
  debug: {desc: 'Debug level [0-10]', label: Debug, value: 0}
  framesPerChart: {desc: Number of data frames per stripchart update, label: Dataframes
      per stripchart update, value: 10}
  framesPerEye: {desc: Number of data frames per mirror eye update, label: N-dataframes
      per mirror eye update, value: 1}
  framesPerLabel: {desc: Number of data frames per labeled-value update, label: N-dataframes
      per labeled value update, value: 10}
  framesPerMountPlot: {desc: Number of data frames per tiptilt mount plot update,
    label: Dataframes per TipTilt mount plot update, value: 5}
  framesPerSH: {desc: Number of data frames per SH eye, label: N-Dataframes per SH
      eye update, value: 1}
  framesPerSHArrow: {desc: N-dataframes per SH-arrow update, label: Dataframes per
      SH-arrow update, value: 2}
  hoursScaleShift: {desc: Sripchart Hours-scale left-shift in seconds, label: Plot
      buffer-size, value: 1800}
  minutesScaleShift: {desc: Sripchart Minutes-scale left-shift in seconds, label: Plot
      buffer-size, value: 60}
  rtDataHost: {desc: Realtime-data host, label: Rtd-host, value: 133.40.163.187}
  rtDataPort: {desc: Realtime-data command port, label: RtdCmd-port, value: 25010}
  secondsScaleShift: {desc: Sripchart Seconds-scale left-shift in seconds, label: Plot
      buffer-size, value: 10}
  stripchartBufferSize: {desc: Sripchart buffer-size, label: Plot buffer-size, value: 43200}
  stripchartHours: {desc: N-Hours buffered by stripchart, label: Plot buffer-size,
    value: 12}
  stripchartTzone: {desc: Realtime-data command port, label: RtdCmd-port, value: LOC}
  verbose: {desc: 'Verbosity level [0-10]', label: Verbose, value: 0}
hdfgain:
  alarmHi: {desc: '', enable: false, label: 'Hdf gain high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Hdf gain low alarm ', value: 0.0}
  dataNdx: 15
  desc: High Order Wavefront Sensor Defocus Gain
  label: HdfGain
httgain:
  alarmHi: {desc: '', enable: false, label: 'Htt gain high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Htt gain low alarm ', value: 0.0}
  dataNdx: 14
  desc: High-Order Wavefront Sensor TipTiltgain
  label: HttGain
ldfgain:
  alarmHi: {desc: '', enable: false, label: 'Ldf gain high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Ldf gain low alarm ', value: 0.0}
  dataNdx: 17
  desc: Low-order wavefront-sensor defocus gain
  label: LdfGain
loopStatus:
  alarmHi: {desc: ' ', enable: false, label: ' ', value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: ' ', value: 0.0}
  dataNdx: 5
  desc: Loop Status
  label: Status
lttgain:
  alarmHi: {desc: '', enable: false, label: 'Ltt gain high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Ltt gain low alarm ', value: 0.0}
  dataNdx: 16
  desc: Low Order Wavefront Sensor TipTilt gain
  label: LttGain
psbgain:
  alarmHi: {desc: Psub gain high alarm, enable: false, label: Psub gain high alarm,
    value: 0.0}
  alarmLow: {desc: Psub gain low alarm, enable: false, label: Psub gain low alarm,
    value: 0.0}
  dataNdx: 10
  desc: PSB gain
  label: PsbGain
psbgainHold:
  alarmHi: {desc: '', enable: false, label: 'Psub gain hold high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Psub gain hold low alarm ', value: 0.0}
  dataNdx: 11
  desc: PSB gain hold
  label: hold
shAvg:
  alarmHi: {desc: ' ', enable: false, label: sh Avg high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: sh Avg low alarm, value: 0.0}
  dataNdx: 59
  desc: Shack-Hartmann average
  label: Avg
shDefocus:
  alarmHi: {desc: sh Defocus high alarm threshold, enable: false, label: sh Defocus
      high alarm, value: 0.0}
  alarmLow: {desc: sh Defocus low alarm threshold, enable: false, label: sh Defocus
      low alarm, value: 0.0}
  dataNdx: 64
  desc: Shack-Hartmann defocus
  label: Defocus
shMax:
  alarmHi: {desc: ' ', enable: false, label: sh Max high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: sh Max low alarm, value: 0.0}
  dataNdx: 57
  desc: Shack-Hartmann maximum
  label: Max
shRmag:
  alarmHi: {desc: ' ', enable: false, label: sh Rmag high alarm, value: 0.0}
  alarmLow: {desc: ' ', enable: false, label: sh Rmag low alarm, value: 0.0}
  dataNdx: 60
  desc: Shack-Hartmann R-mag
  label: Rmag
shTiltX:
  alarmHi: {desc: sh TiltX high alarm threshold, enable: false, label: sh TiltX high
      alarm, value: 0.0}
  alarmLow: {desc: sh TiltY low alarm threshold, enable: false, label: sh TiltY low
      alarm, value: 0.0}
  dataNdx: 61
  desc: Shack-Hartmann X-axis tilt
  label: TiltX
shTiltY:
  alarmHi: {desc: sh TiltY high alarm threshold, enable: false, label: sh TiltY high
      alarm, value: 0.0}
  alarmLow: {desc: sh TiltY low alarm threshold, enable: false, label: sh TiltY low
      alarm, value: 0.0}
  dataNdx: 62
  desc: Shack-Hartmann Y-axis tilt
  label: TiltY
sheye:
  alarmHi: {desc: Shack Hartmann eye high alarm, enable: false, label: Shack Hartmann
      eye high alarm, value: 0.0}
  alarmLow: {desc: Shack Hartmann eye low alarm, enable: false, label: Shack Hartmann
      eye low alarm, value: 0.0}
  dataNdx: 564
  desc: Shack Hartmann Mirror-Map
  label: Sh Miror-Map
stripchart:
  chart1:
    Id: SC1
    fixedScaleMax: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #1 fixed-scale maximum', value: 101}
    fixedScaleMin: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #1 fixed-scale minimum', value: 0}
    scaleWheelMax: {desc: 'Maximum fixed plotscale wheel value ', label: Scalewheel
        maximum, value: 100000}
    scaleWheelMin: {desc: 'Minimum fixed plotscale wheel value ', label: Scalewheel
        minimum, value: -100000}
    scaleWheelRots: {desc: Fixed plotscale wheel rotations, label: Scalewheel maximum,
      value: 10000}
    zeroScaleBase: {desc: Set minimum Y-axis scale = zero, label: ZeroScaleMin, value: false}
  chart2:
    Id: SC2
    fixedScaleMax: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #2 fixed-scale maximum', value: 101}
    fixedScaleMin: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #2 fixed-scale minimum', value: 0}
    scaleWheelMax: {desc: 'Maximum fixed plotscale wheel value ', label: Scalewheel
        maximum, value: 10000}
    scaleWheelMin: {desc: 'Minimum fixed plotscale wheel value ', label: Scalewheel
        minimum, value: -10000}
    scaleWheelRots: {desc: Fixed plotscale wheel rotations, label: Scalewheel maximum,
      value: 1000}
    zeroScaleBase: {desc: Set minimum Y-axis scale = zero, label: ZeroScaleMin, value: false}
  chart3:
    Id: SC3
    fixedScaleMax: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #3 fixed-scale maximum', value: 6}
    fixedScaleMin: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #3 fixed-scale minimum', value: 0}
    scaleWheelMax: {desc: 'Maximum fixed plotscale wheel value ', label: Scalewheel
        maximum, value: 10000}
    scaleWheelMin: {desc: 'Minimum fixed plotscale wheel value ', label: Scalewheel
        minimum, value: -10000}
    scaleWheelRots: {desc: Fixed plotscale wheel rotations, label: Scalewheel maximum,
      value: 100}
    zeroScaleBase: {desc: Set minimum Y-axis scale = zero, label: ZeroScaleMin, value: false}
  chart4:
    Id: SC4
    fixedScaleMax: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #4 fixed-scale maximum', value: 10}
    fixedScaleMin: {desc: 'Maximum fixed plotscale wheel value ', label: 'Stripchart
        #4 fixed-scale minimum', value: 0}
    scaleWheelMax: {desc: 'Maximum fixed plotscale wheel value ', label: Scalewheel
        maximum, value: 10000}
    scaleWheelMin: {desc: 'Minimum fixed plotscale wheel value ', label: Scalewheel
        minimum, value: -10000}
    scaleWheelRots: {desc: Fixed plotscale wheel rotations, label: Scalewheel maximum,
      value: 10}
    zeroScaleBase: {desc: Set minimum Y-axis scale = zero, label: ZeroScaleMin, value: false}
sttgain:
  alarmHi: {desc: Stt gain high alarm, enable: false, label: Stt gain high alarm,
    value: 0.0}
  alarmLow: {desc: Stt gain low alarm, enable: false, label: Stt gain low alarm, value: 0.0}
  dataNdx: 12
  desc: STT gain
  label: SttGain
sttgainHold:
  alarmHi: {desc: '', enable: false, label: 'Stt gain hold high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Stt gain hold low alarm ', value: 0.0}
  dataNdx: 13
  desc: STT gain hold
  label: hold
ttgain:
  alarmHi: {desc: Tiptilt gain high alarm, enable: false, label: Tiptilt gain high
      alarm, value: 0.0}
  alarmLow: {desc: Tiptilt gain low alarm, enable: false, label: Tiptilt gain low
      alarm, value: 0.0}
  dataNdx: 8
  desc: TipTilt gain
  label: TtGain
ttgainHold:
  alarmHi: {desc: '', enable: false, label: 'TipTilt gain hold high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'TipTilt gain hold low alarm ', value: 0.0}
  dataNdx: 9
  desc: Tiptilt gain hold
  label: hold
vmdrive:
  alarmHi: {desc: '', enable: false, label: 'Vm Drive high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Vm Drive low alarm ', value: 0.0}
  dataNdx: 1
  desc: VM Drive Status
  label: Vm Drive
vmfreq:
  alarmHi: {desc: '', enable: false, label: 'Vm frequency high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Vm frequency low alarm ', value: 0.0}
  dataNdx: 2
  desc: VM frequency
  label: VmFreq
vmphase:
  alarmHi: {desc: '', enable: false, label: 'Vm phase high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Vm phase low alarm ', value: 0.0}
  dataNdx: 4
  desc: VM Phase
  label: VmPhase
vmvolt:
  alarmHi: {desc: '', enable: false, label: 'Vm Voltage high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Vm Voltage low alarm ', value: 0.0}
  dataNdx: 3
  desc: VM voltage
  label: VmVolt
wfsTtMountX:
  alarmHi: {desc: '', enable: false, label: WFS tiptilt-mount X high alarm, value: 0.0}
  alarmLow: {desc: '', enable: false, label: WFS tiptilt-mount X low alarm, value: 0.0}
  dataNdx: 74
  desc: Wavefront Sensor TipTilt mount X-axis value
  label: WFS Tiptilt Mount X
wfsTtMountY:
  alarmHi: {desc: '', enable: false, label: WFS tiptilt-mount Y high alarm, value: 0.0}
  alarmLow: {desc: '', enable: false, label: WFS tiptilt-mount Y low alarm, value: 0.0}
  dataNdx: 75
  desc: Wavefront Sensor TipTilt mount Y-axis value
  label: WFS Tiptilt Mount Y
wttgain:
  alarmHi: {desc: '', enable: false, label: 'Wtt gain high alarm ', value: 0.0}
  alarmLow: {desc: '', enable: false, label: 'Wtt gain low alarm ', value: 0.0}
  dataNdx: 18
  desc: Wavefront Sensor TipTilt gain
  label: WttGain
